 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace Tank
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID SendMove = (Nettention.Proud.RmiID)2000+1;
			public const Nettention.Proud.RmiID SendFire = (Nettention.Proud.RmiID)2000+2;
			public const Nettention.Proud.RmiID SendTankType = (Nettention.Proud.RmiID)2000+3;
			public const Nettention.Proud.RmiID SendTankHealthUpdated = (Nettention.Proud.RmiID)2000+4;
			public const Nettention.Proud.RmiID SendTankDestroyed = (Nettention.Proud.RmiID)2000+5;
			public const Nettention.Proud.RmiID SendTankSpawned = (Nettention.Proud.RmiID)2000+6;
			public const Nettention.Proud.RmiID OnPlayerJoined = (Nettention.Proud.RmiID)2000+7;
			public const Nettention.Proud.RmiID OnPlayerLeft = (Nettention.Proud.RmiID)2000+8;
			public const Nettention.Proud.RmiID OnTankPositionUpdated = (Nettention.Proud.RmiID)2000+9;
			public const Nettention.Proud.RmiID OnTankHealthUpdated = (Nettention.Proud.RmiID)2000+10;
			public const Nettention.Proud.RmiID OnTankDestroyed = (Nettention.Proud.RmiID)2000+11;
			public const Nettention.Proud.RmiID OnTankSpawned = (Nettention.Proud.RmiID)2000+12;
			public const Nettention.Proud.RmiID OnSpawnBullet = (Nettention.Proud.RmiID)2000+13;
			public const Nettention.Proud.RmiID P2PMessage = (Nettention.Proud.RmiID)2000+14;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			SendMove,
			SendFire,
			SendTankType,
			SendTankHealthUpdated,
			SendTankDestroyed,
			SendTankSpawned,
			OnPlayerJoined,
			OnPlayerLeft,
			OnTankPositionUpdated,
			OnTankHealthUpdated,
			OnTankDestroyed,
			OnTankSpawned,
			OnSpawnBullet,
			P2PMessage,
		};
	}
}






				 
