
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "Tank_common.h"
namespace Tank {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_SendMove,
               
		Rmi_SendFire,
               
		Rmi_SendTankType,
               
		Rmi_SendTankHealthUpdated,
               
		Rmi_SendTankDestroyed,
               
		Rmi_SendTankSpawned,
               
		Rmi_OnPlayerJoined,
               
		Rmi_OnPlayerLeft,
               
		Rmi_OnTankPositionUpdated,
               
		Rmi_OnTankHealthUpdated,
               
		Rmi_OnTankDestroyed,
               
		Rmi_OnTankSpawned,
               
		Rmi_OnSpawnBullet,
               
		Rmi_P2PMessage,
	};

	int g_RmiIDListCount = 14;

}





